spring:
  config:
    import: optional:dotenv:.env
  datasource:
    url: jdbc:mysql://localhost:3306/mechuragi_db
    username: mechuragi_user
    password: mechuragi_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 56efc6afa5c910f2bf972df5836bf9c9
            client-secret: qtKFtg4lq0w6JuwCKoyOqlelg4eXR9N9
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

jwt:
  secret: mEcHuRaGi2024!sEcReT@kEypR0*jEcT$sPrInG%b00T^sErVeR&s3CuR1ty*

oauth2:
  redirect-uri: http://localhost:3000/oauth2/callback

cloud:
  aws:
    s3:
      bucket: mechuragi-dev-images
    region:
      static: ap-northeast-2
    ses:
      from-email: mechuragi001@gmail.com
      region: ap-northeast-2

aws:
  ses:
    from-email: mechuragi001@gmail.com
    domain: mechuragi.kro.kr

logging:
  level:
    com.mechuragi.mechuragi_server: DEBUG