server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET:mechuragi-dev-images}
    region:
      static: ${AWS_REGION:ap-northeast-2}